Run 2to3 to to fix some installation errors on python3
print() is a function! This fixes:

	➜  gmailfilters git:(master) ✗ python3 setup.py install --user
	running install
	[pbr] Writing ChangeLog
	[pbr] Generating ChangeLog
	[pbr] ChangeLog complete (0.0s)
	[pbr] Generating AUTHORS
	[pbr] AUTHORS complete (0.0s)
	running build
	running build_py
	running egg_info
	writing gmailfilters.egg-info/PKG-INFO
	writing dependency_links to gmailfilters.egg-info/dependency_links.txt
	writing entry points to gmailfilters.egg-info/entry_points.txt
	writing requirements to gmailfilters.egg-info/requires.txt
	writing top-level names to gmailfilters.egg-info/top_level.txt
	writing pbr to gmailfilters.egg-info/pbr.json
	[pbr] Processing SOURCES.txt
	[pbr] In git context, generating filelist from git
	warning: no previously-included files found matching '.gitignore'
	warning: no previously-included files found matching '.gitreview'
	warning: no previously-included files matching '*.pyc' found anywhere in
	distribution
	writing manifest file 'gmailfilters.egg-info/SOURCES.txt'
	running install_lib
	creating /home/lyudess/.local/lib/python3.6/site-packages/gmailfilters
	copying build/lib/gmailfilters/main.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters
	copying build/lib/gmailfilters/__init__.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters
	copying build/lib/gmailfilters/default.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters
	copying build/lib/gmailfilters/util.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters
	copying build/lib/gmailfilters/exceptions.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters
	creating
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd
	copying build/lib/gmailfilters/cmd/applyfilters.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd
	copying build/lib/gmailfilters/cmd/__init__.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd
	copying build/lib/gmailfilters/cmd/managefilters.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd
	copying build/lib/gmailfilters/cmd/dumpconfig.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd
	copying build/lib/gmailfilters/cmd/bulkfilter.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd
	copying build/lib/gmailfilters/cmd/baseclient.py ->
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/main.py to
	main.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/__init__.py
	to __init__.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/default.py
	to default.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/util.py to
	util.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/exceptions.py
	to exceptions.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd/applyfilters.py
	to applyfilters.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd/__init__.py
	to __init__.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd/managefilters.py
	to managefilters.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd/dumpconfig.py
	to dumpconfig.cpython-36.pyc
	byte-compiling
	/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd/bulkfilter.py
	to bulkfilter.cpython-36.pyc
	  File
	"/home/lyudess/.local/lib/python3.6/site-packages/gmailfilters/cmd/bulkfilter.py",
	line 102
	    print '%04d: %s' % (msgid, msg['ENVELOPE'].subject)
			   ^
	SyntaxError: invalid syntax

Which would originally happen if one tried to install these scripts
using python3